# Medicaties in MKA
## Pijnstilling
### Algemene richtlijnen
- Paracetamol/NSAIDS met zwakke opioiden = OK
- Paracetamol/NSAIDS met sterke opioiden = OK
- Zwakke opioiden met sterke opioiden = NIET OK

### Paracetamol - NSAID’s
R/ Paracetamol 1g (co / bruistablet)  

- S/ 4 x 1g /d  
- S/ 4 x 15mg/kg/dag (kinderen)  

R/ Ibuprofen 600mg (co / zakjes)  

- S/ 3 x 600mg/d (max 2.4g/d) (Cave ZS, maagulcera, antico)  
- S/ 3 x 50mg (6m – 2j)  
- S/ 3 x 100mg (2j – 7j)  
- S/ 3x 200mg ( >7j)  

R/ Voltaren 75 mg (co / amp. i.m. –inf)  

- S/ 2 x 75 mg/d

R/ Diclofenac 75 mg  

- S/ 2x 75 mg/d 

R/ Taradyl (NSAID voor postoperatieve pijn) amp. i.m. – i.v. : 5 x 10mg / 1ml  

- S/ 3 x 30mg/d 

### Zwakke opoïden
R/ Tradonal (Tramadol)  

- S/ 100 à 400 mg p.d. in 3 à 4 giften (in 1 à 2 giften voor vertraagde vrijstelling)

R/ Contramal (Tramadol) IV  

- S/ 100 à 400 mg p.d. in 3 à 4 giften (in 1 à 2 giften voor vertraagde vrijstelling)  
  – Jonger dan 70j: 3mg/kg oplaaddosis iv, dan 3mg/kg/6u of 10mg/kg over 24u  
  – Ouder  dan 70j: 1.5-2mg/kg oplaaddosis iv, dan 1.5-2mg/kg/6u of 6-8mg/kg over 24u  
  – Kinderen: 1.5-3mg/kg oplaaddosis iv, dan 1.5-3mg/kg/6u of 6-10mg/kg over 24u  
  - Voeg litican toe (50 mg 3x/d)  

R/ Dafalgan codeïne 500/30  

- S/ tot 3 x p.d. 1 à 2 co  

R/ Zaldiar (Tramadol + paracetamol)  

- S/ tot 3 x p.d. 1 à 2 co  

R/ Dipidolor  

- S/ 20mg per 6 uur, zo nodig na 3u halve dosis bij geven  
  - Jonger dan 70j: 0.25-0.30mg/kg I.M.  
  - Ouder dan 70j: 0.15-0.20mg/kg I.M.  
  - Kinderen: 0.25-0.30mg/kg I.M.  

R/ Catapressan (centraal werkend antihypertensivum) (verlengde werking van Contramal) ook sedatief  

- S/ 1 microgram per kg of 75 microgr oplaaddosis over 15 min + catapressan drip  
  - Dag 1 meestal 900 microgram (=6amp) + natriumchloride 0,9% 50ml  
  - Afbouwschema: 600, 300, 150, stop (telkens over 1 dag)  
  - Bloeddruk controleren  

### Sterke opoïden
R/ Morfine (Morphine HCL Sterop)  

- S/ SC (IV/IM): 10 mg tot max 3x/d  

R/ MS Direct  

- S/ 10mg 3 x /dag (/4u) ( vertraagd = 20mg /12u)  

R/ Durogesic (Morfine)  

- S/ 1 pleister per 72u + Movicol!  

### Neuropathische pijn

## Antibiotica

## Magistrale bereidingen
