# Aangeboren gelaatsafwijkingen en Zeldzame Syndromen
## Indeling
- Classificatie volgens timing insult
  - Malformaties
    - Morfologisch defect orgaan, deel orgaan, lichaamsdeel
    - Door intrinsiek abnormaal ontwikkelingsproces
  - Disruptie
    - Morfologisch defect orgaan, deel orgaan, lichaamsdeel
    - Door extrensieke storing (vasculair, infectieus, mechanisch)
  - Deformatie
    - Abnormale vorm of positie lichaamsdeel
    - Extrinsieke mechanische krachtinwerking
- Classificatie op basis van histologische verandering
  - Hypo/hyperplasie
    - Onder- of overontwikkeling organisme, orgaan, weefsel
    - Door wijziging aantal cellen
  - Hypotrofie/hypertrofie
    - Afname/toename grootte of volume cellen, weefsel, orgaan
  - Agenesie
    - Afwezigheid deel lichaam
    - Door afwezigheid aanleg
  - Aplasie
    - Afwezigheid deel lichaam
    - Door gefaalde ontwikkeling van de aanleg
  - Atrofie
    - Afname normaal ontwikkelde massa
    - Door vermindering celaantal of celvolume
  - Dysplasie
    - Abnormale organisatie van cellen in weefsel
    - Daarvan het morfologisch resultaat
- Klinische classificatie van geboortedefecten
  - Enkelvoudig systeemdefect
    - Grootste groep van geboortafwijkingen
    - Ofwel één orgaansysteem
    - Ofwel één enkele regio
    - multifactoriële oorzaak met beperkt herhalingsrisico
    - vb
      - schisis, congenitale hartafwijking
  - Syndroom
    - Patroon van meerdere afwijkingen
    - Die pathogenetisch verwant zijn
    - Géén enkelvoudige sequentie of polytopisch veldeffect
    - Vb. Van der Woude
  - Associatie
    - Niet op toeval berustend voorkomen in 2 of meer individuen van meerdere afwijkingen
    - Die niet gekend staan als polytopisch velddefect, sequentie of syndroom (CHARGE, VACTERL)
  - Sequentie
    - Patroon of cascade van meerdere afwijkingen
    - terug te brengen tot één primair defect
    - vb. Pierre-Robin
  - Polytopisch veld defect/complex
    - Patroon van afwijkingen
    - Ontstaan door verstoring enkelvoudig ontwikkelingsveld
    - = set van morfologische defecten die tijdens embryogenese één regio aantasten
    - Vb. Hemifaciale microsomie
- Classificatie op basis van medische consequenties
  - Majeure malformaties
    - Als levensverwachting erdoor beperkt wordt
    - OF als normaal functioneren belemmerd wordt in meerdere of mindere mate
    - Soms moeilijk onderscheid tussen mineur en majeur
  - Mineure malformaties
    - Structurele afwijkingen die ofwel geen behandeling nodig hebben ofwel makkelijk behandelbaar zijn
    - En geen blijvende consequenties hebben voor levensverwachting
    - Geïsoleerde mineure malformaties hebben soms familiaal voorkomen
    - BELANG: kunnen wijzen op onderliggende majeure malformatie
      - Hoe groter het aantal mineure, hoe groter de kans op een majeure
      - Kind met 3 of meer mineure malformaties -> 20-90% kans op een majeure
      - Kind met 1 mineure à 3-4% kans op majeure
- Etiologische classificatie
  - Chromosoom
    - Chromosoomafwijkingen
    - Vb. Trisomie
  - Microdeletie
    - Submicroscopische chromosoomafwijking
    - Miv microdeleties
    - Vb. DiGeorge, Prader Willi
  - Teratogenen
    - Gekende teratogenen en prenatale infecties
  - Nieuw dominant
    - Achondroplasie
    - Apert
  - Familiaal
    - Tuberueze sclerose
    - Fragiel X
  - Syndroom
    - Erkende niet familiale, niet chromosomale syndromen
    - Kabuki
  - Geïsoleerde
    - Geïsoleerde anomalieën die niet thuis horen in voorgaande categorie, gastroschisis, geïsoleerde lipspleet
  - Multipele
    - Anomalieën aan meer dan één systeem die niet met elkaar in verband staan zonder unificerende diagnose
    - Vb. VACTERL
    
## Gebruikte indeling in UZ Leuven
### Inleiding
- Wij gebruiken Frans-Nederlandse school van Prof Stricker en Van der Meulen
- Voordelen
  - Zeer MKA chirurgisch ingesteld (beiden craniomaxillofaciaal chirurgen)
- Nadeel
  - Syndromen, associatie en sequenties moeilijker hier in te passen
  - Hiervoor is de classificatie van geboortedefecten beter
- Indeling is sterk beïnvloed door chronologie
  - Fase 1: organisatie
    - Histogenese: eerste twee weken
    - Organogenese: w2 tot w8
      - Fusieprocessen
      - vormveranderingen
  - Fase 2: ossificatie
    - Tot de geboorte
  - Fase 3: adaptatie
    - Eenmaal bot gevormd is
- Deze drie fasen qua pathologie in twee hoofdstukken onderbrengen
  - Groep 1: Alles voor histogenese (tot w2 dus)
  - Groep 2: Organogenese en groei na w2
    - Subgroepen
      - craniofaciale afwijkingen
        - Clefting tussen faciale welvingen voor w8 (schisis)
        - Voornamelijk trimester 1
        - 1/700
      - Dysostose ossificatiecentra na w8 (dysplasie)
        - Voornamelijk trimester 2
        - 1/2500
      - Synostose is desmocranium (synostose)
        - Voornamelijk trimester 3
        - 1/3000
      - Cerebrocraniale afwijkingen
      - Cerebrocraniofaciale dysplasie
      - Cervicale dysplasie

## Andere indelingen
- Neurocristopathieën
  - Gevolg van verstorode migratie, groei en differentiatie van cellen uit neurale lijst
  - Geeft verschillende syndromen
    - CHARGE
    - Waardenburg
    - Treacher Collins
    - Auriculo-condylar syndroom
- Binding aan X-chromosoom
  - Craniofaciale syndromen met X-gebonden overerving
  - Orofacio-digital syndroom type 1
  - Focale dermale hypolasie
  - Lowe syndroom
- Fakomatose
  - Neurocutane aandoeningen
  - Hoofdkenmerk
    - Afwijking huid en centraal/perifeer zenuwstelsel
  - Vroeger 3 aandoeningen
    - Tubereuze sclerose
    - Neurofibromatose
    - Von Hippel Landau
  - Nu > 50 aandoeningen    
## Cerebrocraniale afwijkingen
- Dysplasie waarbij hersenen en neurocranium betrokken is
  - Vb. anencefalie, microcefalie, congenitaal schedeldefect, sluitingsdefect neurale buis
- Volledig sluitingsdefect neurale buis
  - Craniorachischisis
- Gedeeltelijk sluitingsdefect
  - Caudaal
    - Spina bifida aperta
    - Meningocele (enkel vliezen)
    - Meningomyelocele (vliezen + ruggenmerg)
  - Rostraal
    - Zz’er dan caudaal
    - Cranium bifidum apertum -> hersenen niet of partieel tot ontwikkeling + neurocranium niet gevormd
      - Anencephalia totalis: niet met leven verenigbaar
      - Anenchephalia partialis
      - Exencephalia
    - In alle gevallen zijn de ogen normaal ontwikkeld
- Gebruik van FZ tijden periconceptieperiode 4w en 8w na conceptie voorkomt 70% van deze defecten
 
## Fusiestoornissen en schisis
### Primaire aangezichtsspleten
- Ontstaan voor de zevende week in utero
- = lip-, kaak- en verhemeltespleten
  - Latero-nasomaxillaire spleet (naso-oculair)
  - Medio-nasomaxillaire spleet (cheiloschisis – prepalatinale spleet)
  - Intermaxillaire spleet (palatoschisis)
  - Maxillomandibulaire spleet (macrostomie-microstomie)

### Secundaire aangezichtsspleten
- Ontstaan na zevende week in utero   
  - Zeer zeldzaam: 1:150 000 geboorten
  - Niet erfelijk
- Van mond tot voorhoofd
  - Volgens vast patroon van embryonale fusielijnen
  - Betrokkenheid van mond, neus, ogen en oren -> abnormale ontwikkeling
  - Van gering tot ernstig
- Ogen
  - Spleet in ooglid = coloboom
  - Traankanaal probleem
  - Oog onderontwikkeld (microphtalmus)
  - Oog afwezig (anophtalmus)
  - Onderontwikkeling orbita tot teleorbitisme
- Neus
  - Aplasie tot spleetvorming tot dubbele aanleg
- Lip
  - Secundaire spleet vaak op andere plaats dan primaire lipspleet (klassieke cheiloschisis)

### Lip-, Kaak- en Gehemeltespleten
#### Pathogenese
- Embryologische fusie van processie
- Deze fusie is verhinderd bij schisis door
  - Onvoldoende uitgroei aangezichtswervingen
  - Onvoldoende adhesie welvingen -> deficiënte epitheelplaatvorming
  - Persisteren epitheliale plaat (geen apoptose)

#### Embryologie
- Primair vs secundaire palatumspleten
- Primair
  - Voor regio van foramen incisivum = alveolaire kaakregio + voorste deel palatum durum
  - Sluit van achter naar voor in week 6 en 7 van ontwikkeling
  - Als laatste sluit de lip (meest anterieur)
  - ° lip en kaakpleet
    - Door gebrek aan merging van processi fronto-nasalis medialis en lateralis in w4-w7
    - Misvorming beperkt tot primaire palatum
- Secundair
  - Achter foramen incisivum = achterste deel palatum durum + palatum molle
  - Sluit van voor naar achter tussen w8-w12
  - Als laatste sluit de uvula
  - °palatumspleet
    - Indien processi palatini niet sluiten tussen w7-w14
- Extra info
    - Uit knaagdierstudies: rechter palatinale blad bereik eerst middellijn à links blijft altijd wat meer vatbaar voor problemen
    - Ingroei mesenchym gedeeltelijk à ° submuceuze spleet
    - Bifide uvula à soort schisis (cave velofaryngeale insuf + Loeys Dietz syndrome)

#### Erfelijkheid
- Anamnese
  - 75% heeft geen familie met zelfde afwijking
  - Indien toch familiaal voorkomen: erfpatroon is polygenetisch met wisselende penetrantie
- Belang genetica
  - Heeft belangrijke rol bij ontstaan
  - Echter veel vraagtekens over juiste genetisch patroon
  - Lipspleten (+andere spleten associatie) en geïsoleerde gehemeltespleet zijn twee verschillende ziekten met aparte genetica!!
  - Risico op schisis neemt toe als familielid schisis heeft
  - Welke frequentie van schisis kan verklaard worden vanuit gekende factoren?
    - 3% FGF (fibroblast growth factor)
    - 2% MSX1 (muscle segment homeobox 1)
    - 4% maternal cigarette smoking
    - 6% many private mutations in candidate genes
    - 12% IRF6 (interferon regulatory factor 6)
- Rol van genen bij ontwikkeling CLP
  - Beide ouders niet aangetast + 1 kind al met schisis = 2-5% kans op volgend kind met schisis
  - Kans wordt 9% als er al 2 kinderen zijn
  - 1 aangetaste ouder + 1 aangetast kind -> kans op herhaling 14%

#### Prenatale diagnostiek
- Gouden standaard = prenatale echo
  - 3 echo’s terugbetaald door riziv tijdens zwangerschap (1/trimester)
    - 1: 11-13de week
    - 2: 18-22ste week: Dit is de 20w anomaliescan
    - 3: 30-34e w
  - Blijft moeilijk met lage detectieratio
  - Toekomst -> MRI?
- Lipspleet
  - Ten vroegste vanaf 15w in theorie via echo
  - Echter soms over hoofd gezien
  - Ideaal: 12w transvaginale echo door expert
- Verhemeltespleet
  - Detectie op 20w scan:
    - 54-80% in Nederland
    - Stijgt naar 76-82 indien bijkomende malformatie (aandacht stijgt)
  - Heel onderzoekersafhankelijk
  
#### Etiologie
- Erfelijk patroon dat deformatie veroorzaakt OF exogene factoren OF combo
- Erfelijke factoren
  - Met begeleidende afwijkingen heeft =/= dan zonder
  - LKG Vooral bij mannen, vooral polygeen
  - Gehemeltespleet vooral bij vrouwen, vooral dominant met wisselende penetrantie
  - Enkele specifieke syndromen 
    - Spleet als majeur kenmerk
    - Autosomaal dominant
    - Vb. Van der Woude
- Exogene factoren
  - 3/5 van LKG en 4/5 van de G schisis is de familiale anamnese negatief
  - Mutaties of exogene factoren in eerste trimester zijn dan de oorzaak
  - Voorbeelden
    - Hoge leeftijd ouders (significant)
    - Medicatie: thalidomide, fenytoïne, valproaat, topiramaat, methotrexaat
    - FZ tekort
    - Roken, alcohol
    - Virale infecties
    - Radiotherapie
    - Obesitas

#### Incidentie
- 2/1000 LKG
- 1/2000-2500 voor geïsoleerde gehemeltespleet
- Echter heden nog lager gezien vroegtijdige echografische diangose -> abortus
- Schisis blijft de 2de van de tien meest voorkomende aangeboren majeure misvormingen

#### Prevalentie
- LKG spleet
  - Laagst bij Afro-amerikanen, hoogst bij Amerikaanse indianen (20,5/10 000)
  - Intermediair in andere groepen
- Isoleerde G
  - Prevalentie constant over rassen
  
#### Soorten schisis
- Primaire schisis
  - Ten gevolgen van uitblijven van fusie = transformatiestoornis
- Secundaire schisis
  - Ten gevolge van dysplasie = differentatiestoornis
  - Denk bij afwezigheid van mediane gelaatststructuur altijd aan cerebro-cranio-faciale dysplasie!
- Geassocieerde afwijkingen
  - Altijd actief gaan opsporen
  - Cardiologische, urologische en extremiteitsabnormaliteiten + soms met chromosomale afwijking = syndromale schisis
  - Leuven
    - 30% van de LKG heeft bijkomende stoornis ander orgaansysteem
    - 22% heeft naast schisis andere afwijking in HH regio
  - > 300 syndromen hebben schisis
  - Geïsoleerde palatoschsis heeft in 50% associatie met bijkomende aangeboren afwijking
  - Volledige LKG heeft MINSTE associatie met bijkomende afwijking
- Vb van syndromen
  - 22q11 deletie syndroom
  - Oro-auriculo vertebrala spectrum
  - Orofaciodigital syndroom
  - Pierre Robin
  - Vaak + micrognathie onderkaak + glossoptosis + palatoschisis à OSAS
  - Apert
  - Stickler
  - Treacher Collins
  - Ectodermale dysplasie
  - Van der Woude
- Unilat of bilat
  - Unilateraal in 80%
  - Bilateraal in 20%
  - Meestal links
  - Partieel vs compleet
  
#### Anatomische defecten
- Afhankelijk wanneer probleem ontstaat
  - W7-w14: secundair verhemelte: palatum
  - W4-w7: primair verhemelte: lip en premaxilla
- Cheiloschisis
  - Laterale zijde filtrum
  - Volledig
    - Neusvleugel afgevlakt en naar lateraal
  - Lichte vorm
    - Inkerving lip en proc alveolaris
  - Subcutaan
    - Huid intact maar spier gespleten
- Cheilognathoschisis
  - Defect tot foramen incisivum
  - Resterend deel hard en zacht verhemelte zijn intact
  - Beperkt tot primair verhemelte
- Cheilognathopalatoschisis
  - Meest frequente vorm
  - Lip, zijdelijngs premaxilla en verder in hard verhemelte mediaal naast septum en zo verder in week verhemelte op middellijn
  - Unilateraal (80%)
    - Septum met hard verhemelte van gezonde zijde vergroeid
  - Bilateraal (20%)
    - Septum en premaxilla geen verbinding met proc. Palatinus
    - Premaxilla ver naar voor en zeer beweeglijk = hazenlip
  - Neiging tot tuba catarre = tubadysfunctie
  - Neiging tot Simonart’s band: huidbrug bij neusopening à vaker bij lip-kaakspleten dan bij volledige LKG spleten
- Geïsoleerde palatoschisis
  - Meer bij meisjes (itt tot rest meer bij jongens)
  - Volledig tot ….
    - Volledig: Dorsaal van premaxilla en gaat tot uvula
      - Geen vergroeiing van septum met palatum
    - Vele tussenvormen van volledig tot uvula bifida tot submuceuze spleet
- Submucosale spleet
  - Alleen schisis van palatale musculatuur
  - Nasale en orale mucosa intact
  - Inspectie bij fonatie
    - Twee strengen in palatum molle naar spina nasalis
    - Oorzaak van velofaryngeale insufficiëntie en nasale spraak (vaak pas diagnose in 4de– 5de levensjaar
  - Vaak bifide uvula, zona pellucida (blauwe schijn middellijn palatum molle) en inkeping achterrand harde verhemelte = Calnan’s Triade
- Bifide uvula
  - Frequent 1/100 personen
  - Meestal volstrekt goedaardig maar kan uiting zijn van:
    - Submucosale spleet
    - Genetisch syndroom

#### Symptomen
- Problemen met
  - Esthetiek
  - Voeding en slikfunctie
  - Gehoor en spraak
  - Tandenstand en kaakrelatie
  - Psychologisch welbevinden
  - Overdraagbaarheid
- Effect van spleet
  - Spleet bovenlip en bodem neusopening -> ° discontinuïteit m. orbicularis oris à afwijkende spierafwijking à aantasting huid, kraakbeen, bot à problemen met groei
- Enkelzijdige LKG spleet
  - Asymmetrische afwijkingen
  - Onderbreking m. orbicularis oris à afwijking lip en neusvleugen + bot en kraakbeen verplaatst door asymmetrische spiertractie
  - Neus is uit- en inwendig vervormd
  - Neusvleugel en septum -> chronische rhinitis + gesloten neusspraak
- Dubbelzijdige LKG-spleet
  - Ongeremde ontwikkeling vomero-premaxillaire complex in anterocaudale richting
  - Laterale maxilla segmenten hebben geen normale groeistimulus = hypoplasie transversaal, sagittaal en verticaal van maxilla
- Bovenkaaksontwikkeling
  - Cfr supra = hypoplasie in drie dimensies
  - Littekenweefsel en trauma door operaties -> nog meer belemmering
- Middengelaat
  - Dished in face
  - Pseudoprognatie van onderkaak
  - Boventandenboog volledig of deels achter en binnen ondertandenboog
  - Verlittekende en hypertrofische onderlip è onderlip heeft compensatoire functionele hypertrofie (° omgekeerde liptrap)
- Tandaanleg-afwijkingen
  - De regel in de schisisregio
  - Spectrum: surnummerairen, malformaties, geminaties
  - Alveolaire spleet: geen bot voor melk en blijvende tanden
    - Hoektand, laterale snijtand en melkmolaren en premolaren nemen ectopische positie in
  - Afwijkend occlusievlak
  - Verticale onderontwikkeling van het middengelaat
- Afunctioneel palatum molle
  - Ontoereikende faryngeale sfincterfunctie = °velofaryngeale incompetentie
  - Nasal escape met open neusspraak -> verminderde verstaanbaarheid
  - Diagnose
    - Orale inspectie
    - Akoestische nasometrie
    - Spiegelproef
    - Endoscopie of fluoroscopie
  - Gewijzigde mobiliteit farynxwand
    - Frequente otitis media serosa
    - Door dysfunctie buis van Eustachius
    - Verminderd gehoor
    - -> gestoorde spraak en taalontwikkeling
- Nasale regurgitatie
- Minimale expressie van schisis onder vorm van
  - Solitaire globulo-maxillaire cyste of vormafwijkingen anterieure boventanden
  - Lijnvormige depressie bovenlip al dan niet met spierprobleem
  - Submucosale palatumspleet -> spraak en slikproblemen
  
#### Gelaatsgroei
Wat bepaalt groei?

- Intrinsieke factoren
- Functionele factoren
- Iatrogene factoren

Intrinsieke factoren

- Onvoldoende stuwing vanuit mesodermale structuren
- Onderontwikkeling processi

Functionele factoren

- Gespleten m. orbicularis oris met abnormale insertie
  - Deviatie middellijn bovenkaak, septum, spina nasalis naar niet-gespleten zijde
  - Divergente tractie aan columella mediaan en neusvleugel lateraal
- Afwijkende tongpositie
  - Spleet zo breed gehouden
- Deviatie neusseptum
- Palatoschsis -> Andere inplanting tensor veli palatini à dysfunctie tuba
  - Slechte aeriatie middenoor -> frequente otitis media = gehoorpobleem -> schoolresultaatprobleem
  
Iatrogene factoren

- Niet-geopereerde volwassen hebben normale sagittale positie maxilla
  - Dit is GEEN argument om niet te opereren
  - Bij 60% van patiënten spraakprobleem en hoorprobleem
- Geopereerde patiënt = maxilla hypoplasie in 3 dimensies
  - Lipsluiting
    - Gunstig effect op vorm bovenkaak
    - Geen nadeling invloed gelaats of dentoaveolaire groei
  - Sluiting palatum
    - Gunstig effect op nasale klanken
    - Nadelig effect op boogvorm (tansversaal)
  - BIG
    - Indien te jong (3-4j) -> verticale onderontwikkeling en lichte sagittale onderontwikkeling
    - Indien op 9-10j -> geen nadelige invloed meer
  - Farynxplastiek
    - Voordeel: oplossen velo-faryngeale insuff
    - Nadeel: OSAS in 10%
    
#### Therapie
Doel van therapie

- Uiterlijk dat zo weinig mogelijk herinnert aan de afwijking
- Goed functionerend gebit en spraak
- Goede verhouding boven-onderkaak/tanden
- Voorkomen en evt. corrigeren van gehoorsverlies
- Evenwichtige psychische ontwikkeling

Schisisteam

- Samenstelling (multidisciplinair)
  - Kaakchirurg
  - KNO
  - Plastisch chirurg
  - Pediater
  - Klinisch geneticus
  - Logopedie
  - Dermatograaf
  - Maatschappelijk werker
  - Mondhygiënist
  - Orthodontist
  - Tandarts
  - Protheticus
  - Psycholoog
  - Sociaal verpleegkundige
  
Behandeling volgens protocol

- Hier kan wel van afgeweken worden. Protocol op maat van de patiënt in overleg tussen disciplines
- 3m-9m-12m-15m-18m-2j-4j-6j-9j-12j-15j-18j
- Technische onderzoeken
  - Klinische en RX foto’s
  - Gipsmodellen
  - Auditieve en optische onderzoeken
  - Betrouwbaar administratief apparaat!!

#### Primaire behandeling
- Inleiding
  - Er zijn verschillende technieken, chirurgen en timing -> geen eensluitend protocol over alle centra
  - Is de methode goed? Pas 15j na datum te beoordelen
    - Kaken en aangezicht volgroeid
    - Groei soms nadeliger beïnvloed door iatrogene schade van opereren dan door misvorming zelf
    - Operatieve ingrepen resulteren altijd in litteken -> groeibelemmerend è minimaliseren van heelkunde en indien mogelijk tot na groeispurt MAAR 4 uitzonderingen
      - Sluiting lip is obligaat
      - Sluiting zacht verhemelte is obligaat
      - R/ velofaryngeale insufficiëntie is op indicatie
      - BIG op +-9j is obligaat
- Sluiten lip
  - Tijdstip
    - Unilat: op 3m
    - Bilat op 3m en 6m
  - Voorafgaande therapie?
    - Doel: alveolaire bogen beter op elkaar richten
    - Orthodontisch plaatje volgens McNeil
    - Lipadhesieprocedure
  - Technieken
    - Oudste: Veau -> recht litteken maar te korte lip
    - Oplossing à Z-plasties
      - Le Mesurier, Tennison, Tennison-Randall
      - Millard + modificaties
      - Bilateral: Manchester
    - Leercurve van chirurg is bepalende factor, niet techniek
  - Anatomie
    - Continuïteit m. orbicularis oris herstellen
    - Lateraal uitgeweken neusvleugen en laterale lip naar mediaal invoegen
    - Doel -> symmetrie herstellen met goede functie (belang reconstructie m. orbicularis)
- Sluiten palatum molle
  - Doel = afsluiten naso- en orofarynx
  - Zo geen regurgitatie langs neus
  - Zo betere spraak
    - Belang van behouden beweeglijkheid
  - Anatomie
    - Belang van welving passavant te houden bij sluiten  
    - Afsluiten door twee spierbogen
      - Concaviteit craniaalwaarts (m. levator veli palatini
      - Concaviteit caudaalwaarts (m. palatopharyngeus
      - Krachtvector in beide richtingen)
      - Resultaat: vector brengt verhemelte naar boven en achter
  - Velumplastiek = sluiten palatum molle
    - 9-12m
    - Voor inprenting spraakmotoriek è zo articulatoire dyspraxie vermijden
    - Palatum durum blijft open!!!
      - Zo geen groeibelemmering in bovenkaak
    - Technieken
      - Widmaier, kriens, Furlow
    - Vaak in combo met buisjes plaatsen
  - Quid combo met sluiten palatum durum?
    - Veel discussie
    - Sommigen samen
    - Sommigen op 18m
    - Sommigen samen met lip
    - Sommigen samen met big
    - Technieken voor gezamenlijk sluiten
      - Von Langebeck, Veau-Wardill-Kilner pushback, Furlow dubbele Z-plastie.
      - Variatie maar intrinsieke spiermobilisatie is gelijk = intravelaire veloplastiek -> palatinale spieren in de mediaallijn gesloten en naar posterieur gebracht
    - Resulaten
      - Spraakontwikkeling als outcome
        - Furlow is meest optimale techniek
        - Minder velofaryngeale insufficiëntie
        - Echter meer fistels bij Furlow groep, zeker indien palataal defect >1cm breed
- Sluiten palatum durum
  - Indien bij sluiting gehemelte enkel molle wordt gedaan à bijkomende ingreep nodig voor BIG
  - Heel veel discussie in literatuur wat je nu best doet
  - Varieert van sluiting op 3M tot sluiting op 12j
- Farynxplastiek
  - Op indicatie tussen 3-6J
  - Ter behandeling van velofaryngeale insufficiëntie indien spraaktherapie faalt
  - Techniek
    - Orticochea (dynamisch sfincter herstel)
    - San Venero Roselli (superior gesteelde farynxachterwand plastiek)
- Osteoplastie
  - BIG = bot in gnatho = Herstellen benige continuïteit thv processus alveolaris
  - Kan bij primair sluiten van de lip of op latere leeftijd
  - Timing 
    - Niet meer primair -> groei problemen
    - Secundair à beter resultaat
      - 8-12j cfr. Doorbraak hoektand
      - Tijdstip baseren op positie en stadium wortelformatie hoektand aan schisiszijde (1/2 en 2/3 wortelvorming)
  - Donorplaats
    - Heupkam, rib of kinbot
    - Kinbot lijkt het best maar vaak te veel bot nodig
  - 3 interventies
    - Verwijderen melkelementen
    - Bottransplantaat
    - Bonding hoektand/snijtand voor doorbraakbegeleiding door orthodontist
- Tonglap
  - Heel rijke geschiedenis in reconstructie defecten in de mondolte
  - Indicatie
    - Uitkomst waar geen geschikte alternatieve reconstructie voorhanden bij middelgroot defect
    - Schsis: herhaalde pogingen tot spleetsluiting
    - Omgevende palatumweefsel is ischemisch, verlittekend en onregelmatig
  - Techniek
    - Anterieur mediaan gesteelde tonglap
    - Al dan niet met nasaal blad
    - Minstens 5mm dik, en 5cm lang
    - Max 2/3 van tongbreedte en basis van 2-3cm
    - Steel na 25 dagen onder lokale doornemen
      - Dan intuberen
      - Tonglapsteel terugplaatsen en bijwerken
    - Correcties palataal mogelijk vanaf 6m
  - Groot voordeel
    - Werkt in ischemische gebieden!! Brengt goede vascularisatie mee
    - Omtrek van tong zal verminderen maar geen problemen met mobiliteit, spreken, slikken en smaak
  - Nadeel
    - Steel moet 2-3w blijven
    - Spreekverbod en vloeibare voeding
- Kaakchirurgische correctie
  - Timing
    - 15-19j
  - Indicatie
    - Pseudoprogeen uiterlijk
    - Omgekeerde beetrelatie met infra-occlusie
  - R/
    - Le Fort 1 osteotomie
    - Of segmentosteotomie
    - Zz met bsso bij
      - Indien maxilla te ver naar voor zou moeten -> velopharygeale insuf
- Overige
  - Neusseptum en rhinoplastie
  - Halithose (maxillaire sinusitis met postnasal drip)
  - Osas
  - Secundaire correcties
  - Litteken camouflage
  - Esthetische thk
  - Implantaten
  - Erfelijkheidsadvies
- Sluiten palatum is belangrijkste
  - Spraak en articulatie
  - Gehoor
  - Ontwikkeling maxilla
  - Invloed uiterlijk door maxillaire onderontwikkeling
  - Invloed van deze factoren op zelfbeeld patiënten

#### Interdisciplinaire samenwerking
Voedingsadvies

- Kort na de geboorte essentieel
- Teaching aan ouders
- Rekening met type voeding (borst of niet)
- Kwaliteitsparameters
  - Groei en lengte kind
  - Luchthappen
  - Verslikken
  - Nasale regurgitatie
  - Flow intake
  - Voedingstijd

Gehoor -> goede spraak

- Gevaar: recidiverende oorontstekingen
- Buis van Eustachius
  - Normaal gesloten
  - Enkel open bij slikken en geeuwen door tractie m. tensor en levator veli palatini
  - Zo luchtdruk middenoor en nasofarynx gelijk brengen
  - Schisis
    - Geen m. tensor en levator in normale positie
    - Geen opening tuba
    - Sereuze otitis -> geleidingsdoofheid
    - R/ diabolo in trommelvlies
- Detectie
  - Audiometrisch onderzoek
  - Beter: impedantiemetrie

Neusseptum

- Deviatie -> oorzaak slechte neusfunctie
  - sinus maxillaripatholgoie
  - scheefstand neus
- Adenoïden dragen bij tot sinusprobleem
  - Adenoidecotmie -> kan open neusspraak geven

Tonsillen

- Amygdalectomie overwegen bij chronische recidiverende angina’s
- Cave beschadiging m. palatoglossus en palatopharyngeus

Spraakontwikkleing

- Goed volgen na sluiten verhemelte
- Functies: spraak, zingen, slikken, kauwen, blazen
- Belangrijkste sociaal -> spraak
- Naast goed functionerend gehemelte is perfect gehoor esssentieel
- Spraakstoornissen à tweeërlei aard:
  - Resonantiestoornis
    - Hypernasaliteit = velum kan niet maximaal sluiten
    - Probleem bij explosieve medeklinkers (p,b,t,d,k)
  - Articulatiestoornis
    - Samenspel van lippen, tong, week gehemelte, gehemeltegewelf en tandenboog
    - Meest storend bij palatoschisis
    - Compensatoir mechanisme om toch afsluiting te krijgen = glottisslag
    - Tongbasis naar achter verplaatsen

Belang van logopedie

- Onderzoek
  - Functie van gehemelte (nasaliteit)
    - Explosieve woorden in zinnen (potteke)
    - Metalen plaat onder neus houden -> ontsnapte lucht detecteren
    - OF fluoroscopie na aanbrengen hydrast op gehemelte (nadeel -> maar één dimensie)
  - Nasofaryngoscopie
    - Belang van beoordelen zijwaartse beweging farynxwand voor prognose faryngoplastiek
- Indien logopedische oefeningen geen verbetering van de nasaliteit brengen -> faryngoplastiek
  - Technieken
    - Schönborg-Rosenthal OF Sanvenero-Rosselli
    - Beiden à gesteelde farynxlap ingedraaid in het gehemelte
    - Best op leeftijd van 7j
    - Anders verkeerde compensatiemechanismen te diep ingeworteld

Bijkomende ingrepen

- Lippenrood in het midden bovenlip corrigeren = Kapetansky-Juri verschuivingsplastiek
- Te korte bovenlip: Abbé-lap
- Fistels in palatum: gesteelde tonglap – buccale mucosale transpositieflap (a. facialis)

Orthodontische behandeling

- Tand- en kaakbeenanomalieën veroorzaakt door
  - Primaire misvorming
  - Fibreuze retractie door heelkunde
- Typisch
  - Asymmetrische verplaatsing processi alveolares
  - Kleinste segment naar binnen met eerste molaar als rotatiepunt
  - ° kruisbeet thv hoektand
  - Rotaties, kipping en dysplasie van tanden nabij de spleet
- Doel:
  - Expansie bovenkaak
  - Voorzichtig: geen scheur in palatinale littekens
  - Lange behandeling met vaak nood tot prothese OF secundaire osteoplastiek

Cariësverzorging

- Soms indruk dat schisispatiënt hogere vatbaarheid heeft
- Waarschijnlijk te wijten aan onregelmatige stand van de tanden -> moeilijke reiniging

Secundaire reconstructies

- Rhinoplastiek en Le Fort osteotomie
- Preprothetiek en implantologie

## Cerebrocraniofaciale dysplasieën
- Afwijkingen hersenen, neurocranium, ogen en aangezichtsschedel
- Voorbeelden
  - Rhinencefale dysplasie: cyclopie, cebocefalie, premaxillaire aplasie, synophtalmus, ethmocefalie
  - Oculo-orbitale dysplasie: anorbitisme, micro-orbitisme en cryptoftalmie
  - Perioculaire dysplasie: blefaro-schisis, blefaro-phimosis, telecanthus
- Ontwikkeling hersenen en zintuigen = belangrijke rol vorming craniofaciale afwijkingen
- Holoprosencefalie
  - Stoornis patroonvorming prosencephalon
  - Typisch
    - 1 ventrikel in het prosencephalon
    - Continuïteit hemisferen over mediaanlijn
    - Gehandicapt en spastisch
    - Oorzaak: mutaties in SHH (echter klein deel van aantallen)
  - In 80-90% gepaard met mediane craniofaciale afwijkingen
    - Agenesie premaxilla, ethomid, neusseptum en mediane deel bovenlip
    - Hypotelorisme à extreme gevallen = cyclopia
  - Problemen met vorming oog (oogplacode)
    - Anoftalmie tot microftalmie
    - Afmeting oogbeker wordt vroeg embryonaal bepaald door grootte oogblassje en ontwikkelende lens
    - Primaire congenitale afakie
      - Afwezigheid lens
      - Ten gevolge van virusinfecties: rubella, ParvoB19
      - Geeft anoftalmie of microfatlime àmicro-orbitisme en hypoplasie aangezicht
- Craniofaciale dysplasie
  - Inleiding
    - Ogen en hersenen normaal
    - Neurocranium en aangezichtsschedel tonen malformaties
    - Alle mogelijke combinaties mogelijk à wij zien meestal dit soort patiënten op MKA
  - Fusie aangezichtsprocessie gehinderd
    - Oorzaken
      - Onvoldoende uitgroei aangezichtswelvingen
      - Onvoldoende adhesie van de welvingen, resulterend in deficënte epitheelplaatvormign
      - Persisteren van epitheliale plaat
    - Spleten die ontstaan door uitgebleven fusie = vier locaties = PRIMAIRE SPLETEN
      - Latero-nasomaxillaire spleet (naso-oculaire schisis)
      - Medio-nasomaxillaire spleet (cheilognathoschisis)
      - Maxillo-mandibulaire spleet (macrostomie-microstomie)
      - Intermaxillaire spleet (palatoschisis)
    - Andere vorm van uitblijvende apoptose -> partieel persisterend van buccofaryngeale membraan ovv orale synechiae
        - Van der Woude syndroom als vb
        
## Dysostosen
- Dysostose = probleem met botproductie in ossificatiecentra
  - Ontwikkelingsstoornis ossificatiecentrum = ° dysostose
  - Klinisch beeld = gelaatsspleet
  - = secundaire spleten = pseudoclefts
  - Hebben geen vaste locaties, gezien ontstaan op plaats van dysplasie
  - Denk steeds aan cerebrocraniofaciale dysplasie (cruciaal middellijnprobleem)
  - Topografisch te rangschikken via craniofaciale helix
    - Helix heeft vorm van letter S
    - Begint aan laterale zijde van schedel = sfenofrontale dysplasie
    - Naar mediaal via os frontale en neus
    - Vervolgens mediaan over neus naar lateraal onder orbita
    - Richting uitwendig oor en ramus
    - Om zo via corpus mandibulae bij symphysis te eindigen =intermandibulaire dysplasie
  - Voorbeelden
    - sfenoïdale dysplasie: meningo-encefalocele,, osteoom, choanale atresie
    - sfeno-frontale en/of frontale dysplasie: benig defect voorhoofd, benig defect orbitadak, wenkbrauw, laterale canthus, haargrens
    - fronto-frontale dysplasie: cranium bifidum occultum, meningocele
    - fronto-naso-ethmoïdale dysplasie, teleorbitisme, meningo-encefalocele
    - frontonasale dysplasie of internasale dysplasie: median cleft face syndrome; bifid nose with median cleft lip;  bifide neus, Tessier nr. 0 spleet
    - nasale dysplasie: proboscis, nasale aplasie, arhinie, nasoschisis, nasale duplicatie
    - Morian I,Tessier nr. 3 spleet
    - Morian II, III, Tessier nr. 4 spleet;
    - dysostosis mandibulofacialis = syndroom van Franceschetti =  Teacher-Collins syndroom
    - microtie, ooraplasie, Goldenhar-syndroom
    - dysostosis otomandibularis of oculo-auriculo-vertebral spectrum (oavs) = hemifaciale microsomie = Goldenhar-syndroom = 1ste ,2de  kieuwboogsyndroom = (hemi) (cranlo) faciale microsomie
    - Hallerman-Streiff-syndroom, otocefalie
    - onderlip-, kaak-, tongspleet
    - acrofaciale dysostose = syndroom van Nager
  - botvorming à belang van bezenuwing/hersenen/spieren/weke delen
    - dit zijn de drivers van botgroei
    - bepalen uiteindelijke vorm
    - agenesie van ooginhoud è geeft onvermijdelijk micro-orbita gezien ontbreken driver
    - = secundaire effecten op bot
  - Meningocoele en encefalocoele
    - Als neurale buis wel gesloten is
    - Maar bovenliggende mesenchymlagen en epidermis hebben stoornis

## Synostosen
- Suturen gevormd zodra botcentra uitgroeien en contact met elkaar krijgen
  - Synostose è abnormale directe fusie van botkernen zonder vorming sutuur
- Onstaan
  - Laat embryonale/vroeg foetale periode
- Grote invloed op uitgroei en vorm schedel
- Synostose = premature ossificatie van suturen
  - Obstakel skeletale ontwikkeling
  - In de richting loodrecht op de sutuur (Virchow’s wet)
  - Compensatoire overgroei in richting parallel aan suturale lijn
- Faciale synostose
  - Binder syndroom
- Craniale synostose
  - Scafocephalie
  - Trigonocephalie
  - Brachycephalie
  - Oxycephalie
  - Anterieure plagiocephalie
  - Posterieure plagiocephalie
- Combinaties van dysostose en synostose
  - Crouzon, Apert, Acro-cefalo-syndactylie, …
  - Veel variatie omdat defecten op verscheidene niveaus manifesteren
  - Voorbeelden
    - Dysostosis craniofacialis (Crouzon)
    - Apert (acrocefalopolysyndactylie type I)
    - Carpenter syndroom (acrocefalopolysyndactylie type II)
    - Muenke

## Dyschondrosis 
- Kraakbenige matrices die malformatief ontwikkelen
- Vb achondroplasie
- Cervicale dysplasie
  - Defecten in transformatie van kieuwbogen
    - Branchiale sinus, laterale sinus cervicalis, branchiale fistel en agenesie van de schildklier
  - Defecten in transformatie van de kieuwzakken
    - Aplasie en hypoplasie van de thymus
  - Soms kleine eilandjes ectodermale cellen in het mesoderm
    - Geven branchiale cysten
    - Thyreoglossuscysten
    - Dermoïde cysten
  
## Dysostosis cleido-cranialis (cleidocraniale dysplasie)
- Genetisch:
  - Heterozygoot autosomaal dominante mutatie: 50% kans op overerving
  - Kan ook spontane mutatie zijn
  - RUNX2 (andere naam: CBFA1)
- Kliniek
  - Pathognomonisch: deels/volledig ontbreken van Claviculae=> schouders makkelijk bij elkaar
  - Craniaal:
    - Brachycefale schedel
    - Uitgesproken frontale & pariëtale welving
    - Vertraagde/afwezige sluiting van craniale suturen (fontanellen/Wormiaanse botstructuren) = Te zien op RX
  - Faciaal
    - Breed voorhoofd
    - Hypoplasie van middengelaat
    - Brede neusbasis
    - Hypertelorisme
    - Hypoplasie van zygoma en pseudoprogenie
  - Oraal
    - Crowding
    - Surnumeraire tanden
    - Vertraagde doorbraak
    - Laattijdige uitval melkdentitie
    - Malocclusie
    - Hoog ogivaal gehemelte
    - Palatoschisis
  - Niet-faciaal
    - Korte conische vingers
    - Brede duimen
    - Smalle borstkas
    - Scoliose
    - Osteoporose op volw leeftijd
    - Dwerggroei
    
## Pierre Robin-sequentie - Pierre Robin syndroom
- Genetisch
  - Robinsequentie is HETEROGEEN=> dus ook verschillende pathogenese mogelijk!
  - 50%: geïsoleerde Robin-Sequentie-mutatie=> LAGE kans op herhaling (5%)
  - 50%: Robin-sequentie geassocieerd aan
  - Sticler (+ myopie) Treacher Collins Velocardiofaciaal 
- Kliniek
  - Micrognathie van onderkaak
  - Glossoptosis= posterieure verplaatsing & retractie van tongCAVE:Na geboorte moeilijk ademen ruglig: cyanose (tong tegen post farynxwand)=> kleine mandibula kan tong niet naar voor houden!=> leg op buik.
  - Gehemeltespleet (secundair palatum)
  - Voedingsproblemen
  - Groeiachterstand
  - Middenoorproblemen: Recurrente otitis media & gehoorverlies.
  - CAVE: Micrognathie kan ook afzonderlijk voorkomenHeel variabele kliniek: kleine onderkaak ó Rudimentaire aanleg mandibula
- Diagnose
  - Obv KLINIEK!!!
- Behandeling
  - 10% nood aan tracheotomie bij geboorte
  - Distractieosteogenese: ENKEL bij NIET-åale vorm!!!
    - Botgreffe/osteochondrale greffe/verlengingsosteotomieën.
    - CAVE: Weke delen-tractie!
  - Sluiting palatoschisis op 12 maanden!
  
## Noonan syndroom
- Epidemiologie
  - 1/1000-1/2500
  - Hoort niet bij de dysplasies!
- Genetica
  - PTPN11 mutatie Chr12 (pG503R; de novo)
  - Spontaan of autosomaal dominant
  - Andere mutaties
    - SOS1
    - KRAS
    - BRAF
    - RAF1
    - NRAS
- Kliniek
  - Afwijkingen Faciaal/Cardiaal/Skelet
  - Faciaal
    - Breed voorhoofd
    - Hypertelorisme
    - Epicantusplooien
    - Schuine palpebrale fissuren
    - Lager ingeplante oren
    - Zakking van bovenste oogleden: pat moet hoofd naar achter houden om te kijken.
  - Oraal
    - Micrognathie
    - Hoog palatum
    - Malocclusie
    - Reusceltumoren
  - Cardiaal:
    - PATHOGNOMONISCHE eigenschappen: diagnose obv al te stellen!
    - Pulmonaal-klep stenose
    - Hypertrofe cardiomyopathie
    - Atriaal septumdefect
  - Skeletaal
    - Pectus excavatum
  - Andere
    - Kort gestalte
    - Korte – brede nek
    - Cryptorchidie
    - Mentale achterstand
    - STOLLINGSSTOORNISSEN (CAVE: INGREEP!!!!)
- Screening
  - Ortho, tele, face, afdrukname, foto’s
  - CBCT
  - Nierfunctie + echo nieren
  - Stollingsset
  - Oftalmologisch nazicht
  - Basis neuropsychologisch nazicht
  - Genetica
  - Groeicurve opvragen
  - Cardiaal nazicht

## Marfan syndroom
- Diagnose
  - Obv Kliniek EN Gent-criteria
  - Familiale anamnese
- Genetica
  - Mutatie FBN1-gen
  - Autosomaal-Dominant
- Kliniek
  - Aandoening skelet/ogen/cardiovasculair/longen
  - Skeletaal
    - Magere personen
    - Lange ledematen
    - Arachnodactylie
    - Gewrichtsinstabiliteit
    - Scoliose
    - Pectus excavatum/carinatum
  - Ogen: TYPISCH!!!
    - Lens-dislocatie
    - Verkleuring ooglens
  - Cardiovasculair
    - Aorta-dilatatie/ruptuur aorta-aneurysma
  - Faciaal
    - Dolichocefale schedel
    - Lang & smal gelaat=> Maxillaire constrictie=> Intra-oraal overlappende tanden & hoog gebogen verhemelte
    - Mandibulaire retrognathie (soms prognathie)
    - Kruisbeet
    - Macrostomie
    - Overmobiele kaakgewrichten (>60mm)
    - Nauwe nasale luchtweg/Open mouth-breathing=> Adenoïd Faciës=> OSAS
  - Oraal
    - kans op cariës
    - Tandwortelmisvormingen
    - Gingivitis/Parodontitis
    - Alveolair botverlies/Hypermobiliteit tanden
- Voorzorgmaatregelen
  - Orale profylaxe: 1x/6 maanden follow-up mondhygiëne
  - Krachtige, aangepaste tandenborstel
  - Topische fluoride applicatie
  - Antibacteriële mondspoeling
  - Orthodontische R/: behoud van gezondheid parodontium
  - Medicatie
    - spirine VERMIJDEN (gezien patienten vaak reeds onder anti-aggregantia)
  - Chirurgisch:
    - Pre-op controle: cardiale pathologie?
    - CAVE: bacteriemie/Endocarditis=> geef pre-op 2gr amoxicilline
    - Bij uitgebreide dentale R/: doe onder sedatie/AA
    - Voorzichtig bij anesthetica met Adrenaline(=> Tachycardie)
    - Monitoring tijdens THK R/:=> Bloeddruk/Systolische intervallen/Aortic pulse wave velocity.
    
## Sturge-Weber syndroom
- Etiologie
  - Zz congenitale vasculaire aandoening
  - Vasculaire malformaties
- Kliniek
  - Vasculaire malformaties !!!
  - Intracraniële vasculaire misvormingen & ipsilaterale, scherp omschreven “wijnvlek”-verkleuring van aangezichtshuid(Naevus Flammeus)=> Meestal nabij N. Ophtalmicus van N. V
  - Wijnvlek volgt distributie van 1ste & 2e tak van N. V
  - Wijnvlek kruist middenlijn NIET!
  - Neurologische afwijkingen:
    - Epilepsie
    - Hemiparese
  - IQ
    - Geboorte: normale intelligentie=> later mentale retardatie
  - Oog
    - Glaucoom
    - Vasculaire malformatie van oog
- Genetica
  - NIET-overerfbaar syndroom
- Diagnose
  - MRI + IV Gadolinium contrast
  
## Hemifaciale microsomie

### Pruzansky classificatie
- I	Minimum mandibular hypoplasia with all structures present
- II	Condyle, ramus and sigmoid notch are present, but with serious alteration in shape and size 
- III	Mandibular ramus can be reduced to a small thin layer of bone, or does not exist

### Pruzansky-Kaban classificatie
- I	Mandibular morphology is normal but small.
- IIA	Mandibular ramus is short but of abnormal size: glenoid cavity in right position and functional.
- IIB	Glenoid cavity is in an altered position, in inferior, medial, and anterior position.
- III	Absence of temporomandibular joint (TMJ)

### Omens classificatie
**O: Asymmetry of the orbit**

- O0	Orbit with normal size and position
- O1	Abnormal orbital size
- O2	Abnormal orbital position (place a position arrow, e.g.: O2↑ for upper, O2↓ for lower)
- O3	Abnormal orbital size and position

**M: Mandibular hypoplasia**

- M0	Normal mandible 
- M1	The mandible and glenoid fossa are small, with a short ramus 
- M2A	The glenoid fossa has an anatomically acceptable position with reference to the opposite TMJ
- M2B	The TMJ is displaced in a lower, medial and anterior way with a severely hypoplastic condyle
- M3	There is a complete absence of ramus, glenoid fossa and TMJ

**E: Deformity of the outer ear**

- E0	Normal Ear
- E1	Mild hypopasia but all structures are present
- E2	Absence of the external auditory canal with variable hypoplasia of the shell
- E3	Lobe poorly positioned with absence of ear. Lobar remnant is generally moved towards a lower anterior position

**N: Nerve involvement**

- N0	There is no facial nerve involvement
- N1	Upper involvement of facial nerve (temporal and zygomatic rami)
- N2	Lower involvement of facial nerve (buccal, mandibular and cervical rami)
- N3	All rami of facial nerve are affected. Other nerves can be involved, such as trigeminal (sensory), hypoglossal and other cranial nerves

**S: Deficiency in soft tissue**

- S0	There is no deficiency of soft tissue nor muscle deficiency
- S1	Minimal soft tissue and minimal muscle deficiency
- S2	Moderate – between both extremes S1 and S3
- S3	Severe soft tissue deficiency due to hypoplasia of subcutaneous tissue and muscle.
