# Speekselklieren
## Embryologie
- 3 grote klieren = ectodermale oorsprong
  - ontstaan uit speekselklierplacodes die invagineren, migreren en glandulaire parenchym wordt gevormd
- Neurale lijst cellen verzorgen
  - myoepitheelcellen
  - mesenchym
  - bezenuwing
- Start productie speeksel
  - mucus prenataal
  - sereus postnataal
- Kleine speekselklieren
  - gemengd ectodermaal – endodermaal

## Anatomische aandachtspunten
- Ductus van Stenon
  - afvoergang gl. parotis
  - mondt uit op papilla parotidea tegenover kroon M2 bovenkaak
    - vaker tandsteen t.h.v. buccaal oppervlak M2 boven
  - kan geraakt zijn bij trauma van de wang
- Ductus van Wharton
  - afvoergang gl. submandibularis
  - mondt uit in caruncula sublingualis langs middellijn
- Ductus Bartholini
  - afvoergang gl. sublingualis
  - die uitmondt in ductus van Wharton
  - Alternatief: vele kleine afvoergangen die rechtstreeks in mondbodem uitkomen (ducti van Rivini)
- Steunweefsel grote speekselklieren
  - bevat veel lymfoïd weefsel
  - klierweefsel en lymfeknopen door elkaar in grote klieren
  - enkel biopt kan zeggen welk systeem aangetast is
  - submandibulaire klier is omkapseld in fasciakamer hals
    - pijn bij zwelling klier
  - lymfeklieren
    - gl. parotis: intraglandulair, intracapsulair en extraglandulair
    - gl. submandibularis: enkel extraglandulair
  - speekselsecretie
    - afhankelijk van arteriële vasculaire flow
    - sereus: ultrafiltraat, gaat tussen de cellen door
    - muceus: via vesikels, doorheen de cellen
    - gl. parotis is enkel ‘s nachts actief of tijdens kauwen
      - nauw verband tussen activiteit gl. parotis en activiteit van kauwspieren
      - n. mandibularis zorgt voor kauwspieren en via ggl. oticum krijg je sympaticus naar de gl. parotis om daar speeksel productie in gang te zetten
    - submandibulaire klier is ook ‘s nachts actief
- Nervi
  - n. lingualis kruist en loopt onder ductus van Wharton in de mondvloer t.h.v. molaren streek
  - n. facialis verdeelt parotis in oppervlakkig en diep deel
   - GEEN natuurlijk klievingsvlak
   - gl. parotis ontstaat van ventraal naar dorsaal
   - n. facialis van occipitaal naar rostraal

## Anamnese
- Leeftijd
  - verschillende aandoeningen zijn leeftijdsgebonden
  - parotiszwelling
    - bij neonaat: hemangioom, lymfangioom, congenitale constructie ducti
    - schoolgaand kind: bof
    - 30-50j: sialose
    - \>45j: tumor (kan ook vroeger!!)
- Verband met de maaltijd
  - typisch bij lithiasis
- Ontstaan
  - acuut, recurrent, chronisch
- Pijnlijk?
  - eerder bij obstructie of infectie-
- Evolutie en duur
  - plots en op en neer = infectieus
  - geleidelijk: tumor
  - geleidelijk met snel tijdens laatste maanden ➞ suggestief voor maligniteit
- Geassocieerde symptomen
  - reuma, oog, droge mond ➞ Sjögren
  - hormonale, neurogene en digestieve problemen ➞ sialose
- Uitstralingsotalgie: 
  - infecties en lithiasis
- Medicatie!
  - belang bij xerostomie

## Klinisch onderzoek
- Palpatie
  - ALTIJD bimanueel
  - bij gl. parotis: check altijd voorste gehemeltepijler
    - tumoren van de diepe lob van de gl. parotis geven zwelling van de verhemeltepijler en niet extra-oraal ➞ klinisch DDx met accessoire speekselklier ➞ onderscheid kan je enkel maken m.b.v. MRI
- Controleer
  - consistentie
  - mobiliteit t.o.v. huid
  - volledige of deel van de klier
  - glad of hobbelig
  - begrenzing
  - comprimeerbaar
  - pijn
    - vaak bij ontsteking
  - uitvoergangen
    - rode papil of etter = ontsteking
    - masseren klier en controle uitgang
- Bilaterale zwelling
  - kan tumoraal zijn: Whartin of MALT-lymfoma
- Kenmerken maligniteit
  - snelle groei (uitzondering: adenoid cystic carcinoma)
  - uitval zenuwen 
  - fixatie tumor in diepte
  - fixatie tumor aan huid
  - induratie + onregelmatigheid 
  - huidinvasie
  - aanwezige halsklieren
  - kan pijnlijk zijn
  - TYPISCH
    - snelle groei
    - pijn
  - pijn en ulceratie zijn niet noodzakelijk tekenen van maligniteit t.h.v. palatum. Zenuwinvasie wél!
- Palatinale zwelling
  - eerst dentogeen uitsluiten 
  - als je dit doet dan is 72% van de resterende zwellingen tumoraal
    - 50% tumor van kleine speekselklier
    - 22% tumor van andere oorsprong
    - en 28% van inflammatoire oorsprong
  - primair palatum ➞ zelden maligne, meestal dentogeeen (abces van front- of hoektand)
  - alle hierachter ➞ meer opletten (unilaterale zwelling voorbij rugae)
  - palatinale tumoren bij jonge patienten zijn zeer maligne
- Voorkeurslokatie speekselkliertumoren
  - 80% parotis
  - 10% submandibularis
  - 9% accessoire speekselklieren
    - 50% palatum
    - 50% rest
  - 1% lingualis
- Tumor kan presenteren als zwelling, maar ook als ulcus
- Zwelling geeft weinig pijn of last en veroorzaakt grote delay van diagnose
    - als zwelling in gl. parotis zit en relatief groot, dan gaat oorlel afstaan

## Technische onderzoeken
### Klassieke opname
- OPG, occlusale opname ➞ nut: radio-opake steen
- Probleem: overprojectie mandibula + soms beperkte calcificatie
- Cave DDx submandibulaire opacificatie : kan tonsilith, fleboliet of osteoom zijn

### CBCT
- Geeft meer info dan supra

### CBCT sialografie
- Radio-opake vloeistof langs afvoergang inspuiten
- Bladerloze boom tot fijnste vertakking
- Nuttig voor 
  - DDx infectie vs tumor
  - evaluatie klierdestructie door infectie
  - diagnose radiolucente steen
  - belang juiste lokatie steen
  - visualisatie strictuur

### CT
- Doe je bij vermoeden inflammatoir proces
- Stralingsbelasting
- N. facialis kan je niet zien
- CT wel superieur voor bot

### MRI
- Voorkeursonderzoek bij vermoeden tumor
- PPV van 57% voor maligniteit en NPV 90% voor maligniteit
- N. facialis is te zien
- Parapharyngeale extensie of perineurale verspreiding te zien
- Beter onderscheid tumor/spier

### MRI sialografie
- Geen nood aan contraststof
- In beeld brengen van ductale systeem
- Vooraf klier stimuleren met citroenzuur
- Specificiteit stenen en stenosen is vergelijkbaar met conventionele sialografie
- Sensitiviteit is lager

### Scintigrafie
- 99mTc pertechnaat
- Nuttig bij Sjögren en Whartin
- Dynamische evaluatie speekselklierfunctie

### Echografie
- Makkelijk beschikbaar
- Geen stralen
- Goedkoop
- Sensitiviteit en specificiteit heel onderzoekersgebonden
- Begeleiden FNAC
- Vaste structuur te onderscheiden van cystische
- Focale structuur te onderscheiden van diffuse
- Vascularisatie beoordeelbaar
- Adenopathie opspoorbaar

### PET
- Niet bruikbaar wegens hoge aantal vals positieven en vals negatieven

### Speekselonderzoek
- Kwantitatief of kwalitatief te onderzoeken
- Kwantitatief
  - moeilijk 
  - 24h speeksel opvangen uit 1 klier
- Kwalitatief
  - elektrolyten bepalen
  - cytologie bepalen
  - hangt af van activiteit klier
- Aspiratiecytologie
  - Onmisbaar bij tumoren
  - PPV voor maligne is 99%
  - NPV maligne is 94%
- Biopsie
  - Wordt meestal niet preop genomen ➞ te groot risico op soiling
  - Wel vriescoupes perop
- Sialoendoscopie
  - Ductale systeem visualiseren (diagnostisch)
  - Ook therapeutische interventie mogelijk, eventueel in combinatie met chirurgie
  - Semi-rigide endoscopen 0,8-1,6mm

## Speekselkliercysten
### Mucocoele
- Fluctuerend gezwelletje op lip of wangmucosa
- Zeldzaam groter dan 1cm
- Bolronde verhevenheid
  - lichtrefractie ➞ blauwe schijn
  - vaak op onderlip, zeldzaam bovenlip (denk dan eerder aan pleomorf adenoom)
- Etiologie
  - vermoedelijk door trauma (bijten)
  - extravasatietype
  - beschadiging afvoergang ➞ speeksel verspreidt rond kliertjes
  - geen echte aflijning
  - zeldzaam: echte rerentiecyste
    - vaak op oudere leeftijd
- Behandeling
  - excisie met omliggende cysten

### Ranula
- Speciale vorm mucocoele in mondbodem
- Etiologie
  - retentietype: omlijnd door membraan (dun)
  - membraan kan vaak ontbreken ➞ dan ontstaan door afsluiting ducti glandula sublingualis
- Uitzicht
  - unilaterale transparante blauwachtige fluctuerende zwelling
  - mondbodem
  - vaak oppervlakkig
  - soms plunging
    - doorbraak door m. mylohyoideus
    - dan heeft mucosa normale kleur
    - haltervorm op MRI
- DDx
  - dermoïdcyste: mediaan gelegen, vast aanvoelend en bedekt door mucosa
  - thyreoglossus cyste: extra-oraal lager te palperen (op en neer bij slikken)
  - AV-malformatie van lymfatische oorsprong
- Behandeling
  - volledige enucleatie
  - barst echter vaak open ➞ marsupialisatie
  - om recidief te vermijden: gl. sublingualis mee verwijderen
  - plunging ranula = via hals verwijderen

### Cyste van de grote speekselklieren
- Zeldzaam
- Klinisch
  - goed afgekapselde ronde zwelling
  - meer naar ventraal dan tumor
  - punctie: speeksel
- Behandeling
  - enucleatie
    - vaak groter probleem dan gedacht
    - noodzaak tot dissectie n. facialis
    - daarom vaak marsupialisatie naar intra-oraal 

### Sialocoele
- Geen echte cyste, want geen wand (eerder een lekkage)
- Extravasatie van speeksel
  - congenitaal
  - posttraumatisch
  - postoperatief
- Behandeling
  - drainage naar intra-oraal voor 3 maand, maar is wel zeer onaangenaam
  - als dit niet lukt
    - drukverband
    - botoxinfiltratie
    - scleroserende productmix (Picibanil®, TissueCol® en bleomycine)

## Sialoadenose
- Wat is het?
  - sialose
  - niet-inflammatoire aandoening
  - voornamelijk parotis
  - door metabole stoornis
- 3 typische kenrmerken
  - klinisch: niet-pijnlijke recidiverende zwelling, vaak bilateraal, niet inflammatoir en geen verband met maaltijd ⇒ weinig last
  - functioneel: hypo- tot asialie
  - etiologie: deelmanifestatie algemene ziekte
    - bij endocriene aandoening: DM, hypothyroïdie, diabetes insipidus, acromegalie, zwangerschap, menopauze
    - dystrofische metabolische sialoadenose: vitaminedeficiëntie, eiwittekort, alcoholisme, anorexia, boulimia
    - medicamenteus: psychotropica, antihypertensiva, sympathomimetica
    - HIV: >8 jaar besmetting + bilaterale parotiszwelling + xerostomie = diffuse lymphocytosis syndrome (DILS)
- Histologie
  - vebreding acini
  - afwezig onstekingsinfiltraat
- Behandeling
  - ontgoochelend
  - onderliggende aandoening behandelen ➞ toch weinig beterschap speekselklier

## Sialoadenitis
### Inleiding
- Infectieus of niet-infectieus
- Virus vs bacterie bij infectieuze
- Sarcoidose of Sjögren bij niet-infectieuze

### Virale sialoadenitis
#### Parotitis epidemica (bof)
- Voorkomen
  - tussen 2-14 jaar
- Etiologie
  - bofvirus = paramyxovirus (RNA-virus)
  - enkele dagen voor uitbreken tot 1 week erna is patiënt infectieus door speekseldruppels
- Kliniek
  - pijnlijke vast-elastische zwelling gl. parotis ⇒ oorlel staat af
  - lichte koorts, hoofdpijn, trismus, pijn bij kauwen
  - malaise
  - 75% heeft bilaterale zwelling
  - zwelling neemt na 1 week af en alles terug ok na 2 weken
- Diagnose
  - via complement-bindingsreactie op bloed
  - eens doorgemaakt ➞ levenslang immuun
  - vaccin bestaat
- Complicaties
  - orchitis 10-30% van de gevallen ➞ kan tot steriliteit leiden
  - meningo-encephalitis 0,5%

#### Andere
- Denk bij parotitis ook aan andere virale infecties
  - Coxsackie A, echovirus
  - Coxsackie B, Influenza A, CMV, EBV en HIV

### Bacteriële sialoadenitis
#### Inleiding
- Ontstaan door obstructie ductale systeem
- Door verminderde speekselproductie
  - bacteriën kunnen retrograad klier binnen

#### Acute purulente sialoadenitis
- Voorkomen
  - niet-obstructieve vorm steeds aangetroffen in gl. parotis
  - obstructieve vorm steeds in gl. submandibularis
  - 10% bilaterale gl. parotis
- Etiologie
  - ascenderende besmetting
  - enkel in voorbeschikkend milieus van minder speekselsecretie
    - dehydratatie
    - minder weerstand
    - preterminaal
    - postop
      - zagen we vaak bij grote abdominale operaties
      - heden minder door beter beleid vochtbalans + AB
  - Staphylococcus aureus
- DDx: abces van wijsheidstand
- Klinisch
  - harde pijnlijke zwelling parotisloge
  - rode opgespannen huid
  - etterdruppel kanaal van Stenon
  - zeldzaam fluctuatie
- Behandeling
  - parenterale AB
  - strikte mondhygiëne
  - voldoende vocht
  - incisie en drainage
    - enkel bij verweking
  - blijft gevaarlijke aandoening door zwakke algemene toestand

#### Chronische recidiverende parotitis volwassene
- Symptomen
  - recidiverende, maaltijdsgerelateerde, weinig pijnlijke zwelling van één of beide parotiden
  - spontane regressie na enkele dagen/weken
  - dan onvoorspelbaar recidief
- Kliniek
  - uitwendig: weinig tekens van inflammatie
  - intra-oraal
    - rode uitmonding kanaal
    - druppel etter bij massage
  - soms vooraf gegaan door ernstige episode van acute parotitis
    - schade aan ductaal systeem ⇒ stenosen ⇒ bemoeilijken speekselafvloed ⇒ chronische obstructieklachten
    - acini ook beschadigd door ontsteking
  - oorzaak vaak door obstructie ductus van Stenon
    - speekselsteen
    - slijmprop
    - vernauwing
    - ⇒ speekselstase ⇒ retrograde bacteriële infectie
  - andere oorzaken
    - Sjögren
    - Behandeling met radioactief jodium
- Sialografie
  - toont dilatatie afvoergang en talrijke dilataties parenchym = apfelblütenbeeld
  - zien we dan vaak ook aan klinisch niet-aangetaste kant
- APO
  - duidelijk inflammatoir infiltraat parenchym
  - duidelijke dilatatie ducti
  - gevorderd stadium = destructie lobulaire structuur
- Prognose
  - chronisch recidiverende parotitis ➞ kent ongunstige evolutie
- Behandeling
  - interventionele sialoendoscopie
  - afbinden ductus
  - 75% gunstig resultaat
  - parotidectomie in uiterste noodzaak
  - zeer moeilijk door chronische ontsteking
  - schade n. facialis, facialisparese

#### Juveniele recidiverende parotitis
- Voorkomen
  - 2-15 jaar
  - jongens > meisjes
  - na bof, meest frequente aandoening van de gl. parotis op deze leeftijd
  - verdwijnt spontaan na puberteit
- Kliniek
  - recidiverende acuut optredende enkelzijdige zwelling
  - pijn
  - twee weken
  - dan klachtenvrije periode van enkele maanden
- Klinisch onderzoek
  - geïndureerde en palpatiepijnlijke klier
  - massage: etterig speeksel uit papilla parotidea
- Behandeling
  - pijnstilling
  - interventionele sialoendoscopie
  - gunstige prognose

### Specifieke sialoadenitits
- Granulomateuze vorm
  - Zeldzaam
  - Enkel diagnose door APO en bacteriologisch onderzoek
  - Uit te sluiten: TBC, atypische mycobacterie, actinomycose, kattenkrabziekte, toxoplasmose, syphilis, schimmelinfectie (histoplasmosis, blastomycosis)
- Systemische vorm
  - Vaak uiting van onderliggende systemische aandoening
  - Sarcoidose
    - reuscelgranulomen (cfr. TBC zonder verkazing)
    - lymfeklieraantasting, maar speekselklier kan ook (1-6% van de gevallen)
    - éénzijdige parotiszwelling met vaste consistentie
    - syndroom van Heerfordt/uveoparotitis
      - uveitis
      - pijnloze bilaterale parotiszwelling
      - matige koorts
      - soms geassocieerde letsels: aantasting craniale zenuw, erythema nodosum
      - diagnose d.m.v. biopsie
  - Wegener
  - Lupus 
  - Sjögren
  - IgG4-gerelateerde ziekte
- Syndroom van Mikulicz
  - Vage beschrijving van bilaterale parotiszwelling
  - Nutteloze beschrijving

## Sialolithiasis
- Waar?
  - Gl. submandibularis
    - 90% van de stenen
    - 80% is hier radiologisch zichtbaar
    - kunnen groot volume aannemen
    - vaak in ductus van Wharton, net voor orificium
    - 15% zit intraglandulair
  - Gl. parotis
    - 10% van de stenen
    - 50% is hier radiologisch zichtbaar
    - klein en scherpe stenen
    - meestal net aan voorrand masseter
- Symptomen
  - Vooral bij mannen, volwassenen
  - Pas aanwezig bij obstructie
    - tijdens maaltijd plots pijnlijke zwelling
    - regressie na maaltijd en dan recidief bij volgende maatlijd
  - Tijdens koliek kan steen uitgestoten worden
    - indien niet het geval ➞ evolutie naar chroniciteit
    - minder en minder regressie na maaltijd
    - ontstaan van blijvende toestand van hypertrofie + induratie door vorming interstitieel bindweefsel (Küttnerse tumor)
    - zien we bij 1/4 van de submandibulaire stenen gebeuren
- Diagnose
  - Occlusale opname / OPG / CBCT
  - Sialografie (evacuatie opname) indien klinisch vermoeden, maar niets te zien op Rx (radiolucente steen)
  - Niet sonderen
- Behandeling
  - Steen in ductus van Wharton of Stenon
    - Buscopan geven en 1 week later controle om te zien of gruis/steen verdwenen is
    - makkelijk langs intra-oraal verwijderen
    - chirurgisch of sialoendoscopisch of combinatie
  - Steen intraglandulair
    - sialolithotripsie
      - minder vaak toegepast in gl. submandibularis, want je kan vullingen eruit schieten of kaakfractuur veroorzaken
      - 2-10 sessies nodig, elke sessie duurt 30 minuten
      - patiënt 3l per dag laten drinken
    - eventueel extirpatie klier (moeilijk bij parotis)
- Andere oorzaken van calcificatie in de gl. parotis
  - Tumor
    - pleiomorf adenoma
    - ductus carcinoma
    - adenocarcinoma
    - lymphoepitheliaal carcinoma
    - basaal cel carcinoma
    - chondrosarcoma
    - carcinosarcoma
  - Niet-tumoraal
    - AV-malformatie
    - calcificatie in lymfeklier
    - dystrofische calcificatie
  - Systemisch
    - HIV
    - chronisch alcoholmisbruik
    - renale osteodystrofie
    - chronische hoge alkalische fosfatasen
    - lupus
    - Sjögren
    - MALT-lymfoom

## Xerostomie
- Gevoel van droge mond kan door
  - verminderde speekselsecretie
  - voortdurende mondademhaling
  - dik, kleverig speeksel
- Oorzaken
  - medicatie
    - anticholinergica
    - sedativa
    - antidepressiva
    - antihistaminica
    - antihypertensiva
    - spasmolytica
    - anti-epileptica
  - aandoening speekselklier
    - syndroom van Sjögren
    - sialoadenose
    - chronische ontsteking
  - radiotherapie
    - vooral gl. parotis is gevoelig
    - vanaf 30 Gy irreveriebele schade
    - \>40Gy ➞ geen speekselflow meer
    - hoeveelheid mindert maar ook samenstelling verandert
      - viscositeit neemt toe
      - pH daalt
      - toename micro-organismen
  - dehydratie
    - negatieve vochtbalans ➞ minder secretie
    - bij koorts, diarree (langdurig), preterminale dehydratie, nieraandoeningen
  - aandoening zenuwstelsel
    - centraal of perifeer ➞ repercussie op secretie
    - vaak speekselremming
    - kan ook voor overvloed zorgen
  - hormonale stoornis, avitaminose
    - diabetes ➞ droge mond 
      - door meer urinesecretie
      - rechtstreekse inwerking op speekselklierparenchym
    - avitaminose B1, A, E, ijzer (Plummer-Vinson)
  - psychologische factor
    - pas na uitsluiten supra en grondig KO
- Behandeling
  - moeilijke therapie
  - Voornamelijk symptomatisch
  
## Sialorhoea
- Objectief vs subjectief
  - objectief
    - toegenomen productie
    - door pijn, nausea, Parkinson, rabiës, intoxicatie
  - subjectief
    - te weinig wegslikken
    - oropharyngeale dysfunctie sfincter/slikmechanisme
    - macroglossie
- Behandeling
  - oorzaak eerst
  - dan pas symptomatische verlichting met medicatie
  - antihistaminica/anticholinergica/botox
  - chirurgie kan ook: extirpatie klier

## Sjögren
### Inleiding
- Chronische systemische auto-immuunziekte
- Exocrien klierweefsel (speeksel en traanklier) aangetast
- Twee vormen
  - primaire Sjögren = sicca-syndroom
    - droge mond (xerostomie)
    - droge ogen (xeroftalmie)
  - secundaire Sjögren
    - naast sicca, ook auto-immuunziekte
    - vb. RA, lupus…
    - 15% patiënten met RA hebben Sjögren

### Etiologie
- Ongekend

### Epidemiologie
- Frequent voorkomen
- 9x meer bij vrouwen
- Vaak op middelbare tot oudere leeftijd
- Prevalentie in het Westen 1,5%
- Na RA, meest voorkomende auto-immuunziekte
- Zeldzaam in Azië: polyfenolen uit groene thee ondrukken auto-antilichamen

### Symptomen
- Voornaamste: minder secretie traanklier en speekselklier
- Afname speekselsecretie = gevoel droge mond = xerostomie
  - ernst verschilt 
  - kan gepaard gaan met atrofie mucosa
  - eventueel gladde gekloven tong
  - branderig gevoel mondslijmvlies
  - moeite met slikken, smaak, prothese
  - groter risico op cervicale cariës
- Zwelling speekselklieren
  - kan, maar zeldzaam
- Droogheid kan over ganse tractus aerodigestivus 
- Minder traansecretie = droge ogen + branderig gevoel
  -➞ conjunctivitis en keratitis
- Algemene symptomen
  - vermoeidheid en algemene malaise
  - lymfadenopathie, primaire biliaire cirrose, Raynaud, interstitiële nefritis, interstitiële longfibrose, vasculitis, perifere neuropathie

### Sialografie
- Atypische beeld: punctiform beeld in begin, later apfelblüten 
- Scintigrafie ook weinig specifiek

### APO
- Karakteristiek: lymfocytaire infiltraten van T-cellen en atrofie van de acini
- Op termijn: proliferatie van epitheel ducti ➞ beeld van benigne lymfo-epitheliale laesie

### Diagnose
Er zijn zes criteria:

1. oogklachten (subjectief)
2. mondklacht (subjectief)
3. oogafwijking (objectief)
  - Schirmer test: filtreerpapier in onderste conjunctivale zak en bevochtigde lengte meten na 5 min (moet normaal boven 5mm zijn)
  - Bengaals rood op cornea ➞ aanwezigheid epitheeldefect controleren
4. histopathologisch onderzoek lipspeekselklier (want er is algemene aantasting)
5. sialometrisch, grafisch of scintigrafisch bewijs van speekselklieraantasting
6. auto-antilichamen
  - 40% heeft auto-antilichamen tegen SSA
  - 25% heeft auto-antilichamen tegen SSB
  - tot 80% is ANA + (niet als criterium)
  - tot 60% is RF + (niet als criterium)

### Evolutie en prognose
- 40x hoger risico op maligne lymfoom
- 40% van Sjögren ontwikkelt bilaterale parotiszwelling
  - 10% ontwikkelt hiervan een MALT-lymfomen
- Deze tumoren ontstaan 
  - vanuit speekselklierweefsel (extranodaal)
  - vanuit lymfeklieren in speekselklier (nodaal)

### Behandeling
- Causale behandeling Sjögren bestaat niet
- Symptomatische behandeling
  - kunstspeeksel
  - goede tandzorg!! (hogere cariësneiging)
  - medicamenteus: hele waaier
  - succes hangt af van hoeveelheid aanwezig gezond parenchym
- Indien op parotisbiopsie hoog aantal CD20+ B-cellen 
  - reageren goed op rituximab
  - structurele regeneratie van klierweefsel (ducti striati)

## Tumoren
### Voorkomen
- 80% in gl. parotis
  - 80% hiervan is benigne
- 10% in gl. submandibularis
  - 50% benigne
- 1% gl. sublingualis
  - altijd maligne
- 9% accessoire speekselklieren
  - 65% maligne
- Incidentie 3/100.000
- Leeftijd
  - gemiddeld 45 jaar
  - maligne 56 jaar
  - vaker bij Eskimo’s 
- Voorgeschiedenis van RT of kernexplosie
  - hogere incidentie speekselkliertumoren
  - latentieperiode van 15-20 jaar

### Stagering en prognose
- 5YS is hier relatief
  - bij SCC voornamelijk recidief in de eerste 2 jaar en dan stabiel qua overleving
  - bij speekselkliertumor blijft overleving rechtlijnig dalen
- Vaak recidief en metastasering
- Tumoren met low grade malignancy zijn vb. gunstig op 5 jaar, maar heel slecht op 10 jaar
- Bepalen van kans op metastasen ➞ histologische typering van groot belang
- Hematogene metastasen komen vaker voor dan lymfogene

### Soorten gezwellen
- Sialomen = tumoren van speekselklierparenchym
  - kan zowel in grote als kleine speekselklieren
- Synsialomen = tumoren van interstitieel weefsel (bloedvat, zenuw, vetweefsel, lymfoïdweefsel, bindweefsel)
  - vb. hemangioom van de gl. parotis
- WHO 2017  
  - maligne tumoren van de speekselklieren:
    - muco-epidermoïd carcinoma
    - adenoid cystic carcinoma
    - carcinoma ex pleiomorf adenoma
    - adenocarcinoma
    - acinic cell carcinoma
    - salivary duct carcinoma
  - benigne tumoren van de speekselklieren:
    - pleiomorf adenoma
    - Whartin tumor
  - niet-neoplastische epitheliale laesies
  - benigne weke delen laesies
    - haemangioma
  - hematolymfoïde tumoren
    - MALT-lymfoma (extranodale marginale zone lymphoma of mucosa-associated lymphoïd tissue)

### Goedaardige tumoren
#### Pleiomorf adenoom
- Voorkomen
  - synoniem mengtumor
  - benaming: aanwezigheid epitheliale en mesenchymale componenten bij histologie
  - mesenchymaal: myxoïd, hyalien, kraakbeen
  - voornamelijk 50-60 jaar (maak kan op alle leeftijden)
  - meer bij vrouwen
  - voornamelijk in de gl. parotis ➞ 65% van de parotistumoren
  - 8% van de gevallen uitgaande van accessoire speekselklier (grens hard en week verhemelte)
- Klinisch
  - langzaam groeiend: intermittent snellere groei en indolente fase
  - vaak al jaren aanwezig voor ze naar arts komen
  - palpatie
    - goed omkapseld gezwel
    - vaste consistentie
    - buitenste kwab parotis (achter ramus)
    - nauw verbonden met uitwendige gehoorgang
  - vroeger geclassificeerd als semimaligne door
    - sterke neiging tot recidief
    - relatief hoge incidentie van laattijdige maligne degeneratie
- Behandeling
  - conservatieve totale parotidectomie
  - preop géén biopsie wegens gevaar op soiling
  - FNAC mag wel
  - perop vriescoupe
  - indien in palatum: partiële tot subtotatle maxillectomie

#### Cystadenolymfoom/Whartin
- Voorkomen
  - 50-70 jaar
  - 90% bij mannen
  - zo goed als uitsluitend gl. parotis (5-10°% van de tumoren daar)    
  - typisch in de onderpool
  - in 15% zijn er multipele lokalisaties (ipsi- en contralateraal)
- Etiologie
  - sterke band met roken
- Onderzoek
  - scintigrafie
  - palpatie: goed omkapseld en zacht met occasioneel fluctuatie
- APO
  - cystische ruimten tussen epitheliaal en lymfoïd weefsel, omgeven door dun kapsel
- Behandeling
  - excisie
  - lokaal recidief is zeldzaam 
  - maligne degeneratie is zeldzaam

### Kwaadaardige tumoren
#### Muco-epidermoid carcinoma
- Voorkomen
  - geografische verschillen
    - USA: frequentste maligne speekselkliertumor
  - 16% van alle speekselkliertumoren
  - 44% van maligne tumoren die zich ontwikkelen uit voordien bestraalde speekselklieren
  - komt op kinderleeftijd voor!
  - meest frequente
    - maligne speekselkliertumor 
    - maligne speekselkliertumor bij kinderen
    - maligne speekselkliertumor intra-oraal
- Locatie
  - 53% in grote klieren
    - 45% gl. parotis
    - 7% submandibulair
    - 1% sublinguaal
  - 21% accessoire klieren
  - 19% elders
    - onderlip
    - bot boven-onderkaak
- Klinisch
  - asymptomatische zwelling bij 2/3 van de patiënten
  - symptomatische patiënt vertoont pijn, dysfagie, trismus en zenuwuitval
- APO 
  - macroscopisch
    - lijkt op pleiomorf adenoom
    - vast of cystisch (mucus)
  - microscopisch
    - mucus-secreterende en epitheloïde cellen 
    - architectuur: regelmatig zonder tekens van kwaadaardigheid
  - hoge graad van maligniteit
    - cellulaire tumoren met pleiomorf aspect
    - minder slijmproducerende cellen
- DDx
   - necrotiserende sialometaplasie
- Prognose
  - discussie
  - 5YS 90% indien geen positieve klieren ➞ low-grade malignancy
  - overleving hangt voornamelijk af van hoog- vs laaggradig en cytologie
  - ook gezwellen die vanaf het begin heel kwaadaardig zijn
  - eerder regionaal uitbreiden dan metastasen op afstand
  - ook bepaald door radicaliteit ingreep
- Gradering
  - zegt enkel iets over tumoren uitgaande van gl. parotis
  - voor kleine klieren ➞ altijd als hooggradig beschouwen
  - vooral mucineuze cellen of > 10% cysten in gl. parotis = low grade (12% recidief en geen metastasen)

#### Adenoid cystic carcinoma
- Voorkomen
  - 5% van alle tumoren in de grote speekselklieren
  - 25% van alle tumoren in de accessoire speekselklieren-
  - traag groeiend gezwel (cfr. pleomorf adenoma)
- Klinisch
  - op late termijn: uitval zenuwen + botingroei + pijn (perineurale groei)
  - perineurale groei: typisch voor deze tumor ➞ heel sombere prognose
  - insidieus verloop
  - metastasen laten lang op zich wachten
  - toch aanwezig in 50%
  - meestal hematogeen
- Prognose
  - 5YS: 75%
  - 20YS: 15%
  - gemiddelde overleving met longmetastasen is 9 jaar
  - tumorstadium en radicaliteit van de ingreep zijn bepalend

#### Acinic cell carcinoma
- Voorkomen
  - meestal gl. parotis, soms bilateraal
  - kan ook op andere plaatsen
  - langzaam groeiende zwelling (onmogelijk klinisch onderscheid met pleiomorf adenoma)
- APO
  - microscopisch: acinic cell
  - lijkt op cellen van normale sereuze acini
- Prognose
  - sterke neiging tot lokaal recidief
  - kan laattijdig (tot 30 jaar)
  - metastasen ook laattijdig: lymfeklieren, skelet, longen
  - zeer trage evolutie: 90% 5YS = low grade
  
#### Salivary duct carcinoma
- Voorkomen
  - Zeldzaam
  - Meer in mannen, 6e-7e decade
  - Meest frequent in parotis
  - 1/2 heeft reeds facialisuitval 
  - 60% heeft reeds positieve klieren, risico stijgt sterk indien tumor > 3 cm
  - Locoregionaal recidief: 13-48%
  - Recidief op afstand: 32-68%
  - Median survival: 6.6 jaar, 5YS: 64%
- APO
  - Overexpressie HER2, EGFR, androgeen receptor bij >1/3
  - Lijkt op borstcarcinoma van ductaal type (maar negatief voor oestrogeenR, progesteronR)
- Genetica
  - TP53
  - P53 => slechtere prognose
  - Overexpressie androgeenreceptor => betere prognose
- Behandeling
  - Multimodaal
  - Volledige resectie
  - Nekdissectie
    - Minimaal electief bij N0 nek
  - Adjuvant radiotherapie: onduidelijke rol maar gezien agressiviteit toch vaak gedaan
  - Trastuzumab kan overwogen worden bij HER2 expressie single of in combo met chemo (docetaxel, phase II trial had respons rate van 76%, median PF survival 9.8 maand)
  - Bij verdere progressie kan trastuzumab-emtansine overwogen worden
  - Bij androgreenR expressie evt androgeen deprivatie/inhibitie therapie
  

  
  
  
  

#### Andere carcinomen
- Adenocarcinoom, SCC, carcinoom ex pleiomorf adenoma
- Sombere prognose van <50% 5YS

## Niet neoplastische epitheliale laesies
### Benigne weke delen tumoren
#### Hemangioma
- Parotishemangioom is typisch bij zuigeling
- Week aanvoelend gezwel dat groeit bij wenen 
- Heeft pulsaties
- Capillaire dilatatie aan huid 
- Initieel forse groei, vervolgens kleiner worden bij ouder worden
- Afwachtende houding (n. facialis in sterk gevasculariseerd milieu)
- Meest frequente goedaardige speekselkliertumor bij kinderen en exclusief in parotis

### Hematolymfoïde tumoren
#### Voorkomen
- 15% Hodgkinlymfoom
- 85% non-Hodgkinlymfoom
  - meestal MALT-lymfoom, maar alles kan
- Onderscheid tussen primaire lokatie in speekselklier of als onderdeel van uitgezaaid ziektebeeld
- Welke klieren
  - 70% parotis
  - 20% submandibularis
  - 10% kleinere
  
#### MALT lymphoma
- Sjögrenpatiënt heeft hoog risico op evolutie naar MALT-lymfoom
- B-cel neoplasma  
- Mucosa associated lymphoid tissue 
- = Extranodale marginale zone B-cel lymfoom
- 5YS: 82-95%
- Belangrijk aandeel van rituximab in overleving

## Operatieve behandeling
- Gl. parotis
  - volledig in teken n. facialis
  - pleiomorf adenoom = mag normaal geen probleem zijn
    - opzoeken n. facialis net voor en onder uitwendige gehoorgang
    - verschillende takken naar voor toe disseceren
  - acinic cell en muco-epidermoid hangt af van differentiatiegraad + lokalisatie
    - goed gedifferentieerd ➞ behoud n. facialis is mogelijk
    - hoog maligne variant van die tumor ➞ n. facialis verwijderen + microchirurgisch zenuwgreffe plaatsen
    - laattijdige facialisparalyse ➞ R/ met heterolaterale n. facialis anastomose = cross-face anastomose
- Frey syndroom
  - in 20% van de parotidectomieën
  - uitgesproken transpiratie en roodheid geopereerd gebied bij stimulatie speekselsecretie
  - veroorzaakt door wanordelijke regeneratie sympathische vezels n. auriculotemporalis
  - kan je testen met lugol: zweten doet lugol zwart kleuren
  - krijg je met geen enkele behandeling onder controle
  - best werkend
    - lokaal anticholinerge zalf (1-3% scopolamine zalf)
    - eventueel neurectomie plexus tympanicus
    - eventueel botoxinjectie

## Aanvullende radiotherapie 
Aanvullende radiotherapie is nodig bij:

- Positieve of onzekere snederanden
- Extra-glandulaire uitbreiding
- Hooggradige maligniteit
  - hoge graad maligniteit tumor (adenocarcinoma, graad 3 mucoepidermoïd, salivary duct, plaveiselcelcarcinoma, melanoma)
  - bij adenoid cystic carcinoom
  - NIET bij acinic cel carcinoma, low grade mucoepidermoid carcinoma, epitheliaal myoepitheliaal carcinoma
- Perineurale invasie
- Botinvasie
- Regionale lymfeklier
- Lymfovasculaire invasie
- T3-4
- Maligne tumoren >4cm
- Uitbreiding naar diepe kwab


## Informed consent
- Gl. parotis
  - facialis bespreken
  - voosheid n. auricularis magnus bespreken
  - Frey syndroom bespreken
  - sialocoele bespreken
- Gl. submandibularis
  - schade aan ramus marginalis van de n. facialis
  - schade n. lingualis
  - schade nn. hypoglossus
  - lithiasis relicta
  - andere complicaties